#Debezium数据同步配置
timely:
    # 是否开启
    switch: true
    # 偏移量文件
    offset-file-name: C:/Users/liuc8/Desktop/offsets.dat
    # 是否启东时清除偏移量文件
    offset-file-clean: true
    # 偏移量提交时间 单位ms
    offset-time: 1
    # 读取历史记录文件
    history-file-name: C:/Users/liuc8/Desktop/mysql-bin.index
    # 读取的数据库信息
    offline:
        ip: localhost
        port: 3306
        username: root
        password: root
        # 保证每个数据库读取的 instance-name  logic-name 不能相同
        # 实例名
        instance-name: sc-mssql-connector
        # 逻辑名
        logic-name: sc-mssql-customer
        # 读取的表
        include-table: user
        # 读取的库
        include-db: differ

#
#timely:
#    # 是否开启
#    switch: true
#        # 偏移量文件
#        offset-file-name: C:/Users/liuc8/Desktop/offsets.dat
#    # 是否启东时清除偏移量文件
#    offset-file-clean: true
#    # 偏移量提交时间 单位ms
#    offset-time: 1
#        # 读取历史记录文件
#        history-file-name: C:/Users/liuc8/Desktop/mysql-bin.index
#    # 读取的数据库信息
#    offline:
#        ip: localhost
#        port: 3306
#        username: root
#        password: root
#        # 保证每个数据库读取的 instance-name  logic-name 不能相同
#        # 实例名
#        instance-name: instance-name
#        # 逻辑名
#        logic-name: instance-name
#        # 读取的表
#        include-table: user
#        # 读取的库
#        include-db: differ
#        server-id: 1
#
